CRITICAL - 2022-04-12 05:29:11 --> Undefined property: App\Controllers\auth::$db
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 18)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 05:32:51 --> Undefined property: App\Controllers\auth::$db
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 18)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 05:41:17 --> Undefined property: App\Controllers\auth::$db
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 18)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 05:46:08 --> Undefined property: App\Controllers\auth::$db
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 18)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 06:26:07 --> Undefined property: App\Controllers\auth::$db
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 18)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-04-12 07:36:01 --> Unknown column 'gmail' in 'where clause'
CRITICAL - 2022-04-12 07:36:01 --> Unknown column 'gmail' in 'where clause'
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\M_login.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): App\Models\M_login->get_data_login(NULL, 'user')
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-04-12 07:36:04 --> Unknown column 'gmail' in 'where clause'
CRITICAL - 2022-04-12 07:36:04 --> Unknown column 'gmail' in 'where clause'
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\M_login.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): App\Models\M_login->get_data_login(NULL, 'user')
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-04-12 07:36:43 --> Unknown column 'gmail' in 'where clause'
CRITICAL - 2022-04-12 07:36:43 --> Unknown column 'gmail' in 'where clause'
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\M_login.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): App\Models\M_login->get_data_login(NULL, 'user')
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-04-12 07:36:44 --> Unknown column 'gmail' in 'where clause'
CRITICAL - 2022-04-12 07:36:44 --> Unknown column 'gmail' in 'where clause'
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\M_login.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): App\Models\M_login->get_data_login(NULL, 'user')
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-04-12 07:41:18 --> Unknown column 'gmail' in 'where clause'
CRITICAL - 2022-04-12 07:41:18 --> Unknown column 'gmail' in 'where clause'
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\M_login.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): App\Models\M_login->get_data_login(NULL, 'user')
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-04-12 07:42:50 --> Unknown column 'gmail' in 'where clause'
CRITICAL - 2022-04-12 07:42:50 --> Unknown column 'gmail' in 'where clause'
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\M_login.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): App\Models\M_login->get_data_login(NULL, 'user')
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-04-12 07:42:51 --> Unknown column 'gmail' in 'where clause'
CRITICAL - 2022-04-12 07:42:51 --> Unknown column 'gmail' in 'where clause'
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\M_login.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): App\Models\M_login->get_data_login(NULL, 'user')
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-04-12 07:42:52 --> Unknown column 'gmail' in 'where clause'
CRITICAL - 2022-04-12 07:42:52 --> Unknown column 'gmail' in 'where clause'
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\M_login.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): App\Models\M_login->get_data_login(NULL, 'user')
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-04-12 07:42:52 --> Unknown column 'gmail' in 'where clause'
CRITICAL - 2022-04-12 07:42:52 --> Unknown column 'gmail' in 'where clause'
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\M_login.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): App\Models\M_login->get_data_login(NULL, 'user')
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-04-12 07:42:52 --> Unknown column 'gmail' in 'where clause'
CRITICAL - 2022-04-12 07:42:52 --> Unknown column 'gmail' in 'where clause'
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\M_login.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): App\Models\M_login->get_data_login(NULL, 'user')
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-04-12 08:01:05 --> Undefined property: App\Controllers\Auth::$db
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 20)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 08:04:17 --> Undefined property: App\Controllers\Auth::$db
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 20)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 08:05:30 --> Undefined property: App\Controllers\Auth::$db
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 20)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 21:09:26 --> Undefined property: App\Controllers\Auth::$db
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 20)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 21:17:40 --> Class "app\Models\M_login" not found
#0 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-04-12 21:50:37 --> Class "app\Models\M_login" not found
#0 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-04-12 21:52:14 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 27)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 21:58:23 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\ci4\system\Model.php(545): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\ci4\system\Model.php(722): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(24): CodeIgniter\Model->__call('where', Array)
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#4 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-12 22:00:45 --> Undefined array key "user_password"
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 26)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 22:51:20 --> Call to a member function where() on array
#0 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-04-12 22:52:15 --> Attempt to read property "password" on array
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'C:\\xampp\\htdocs...', 26)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 22:54:54 --> Undefined property: App\Controllers\Auth::$db
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 21)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 22:55:15 --> Undefined property: App\Controllers\Auth::$pembelian
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 21)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 22:55:37 --> Call to undefined method App\Controllers\Auth::table()
#0 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-04-12 22:56:01 --> Undefined property: App\Controllers\Auth::$table
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 21)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 22:57:31 --> Undefined property: App\Controllers\Auth::$db
#0 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 21)
#1 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#2 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-12 23:02:09 --> Invalid file: VLogin.php
#0 C:\xampp\htdocs\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('VLogin.php')
#1 C:\xampp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('VLogin', Array, true)
#2 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(47): view('VLogin')
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#4 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-12 23:02:59 --> Invalid file: /.php
#0 C:\xampp\htdocs\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/.php')
#1 C:\xampp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('/', Array, true)
#2 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(47): view('/')
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#4 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-12 23:03:04 --> Invalid file: /.php
#0 C:\xampp\htdocs\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/.php')
#1 C:\xampp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('/', Array, true)
#2 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(47): view('/')
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#4 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-12 23:03:31 --> Invalid file: .php
#0 C:\xampp\htdocs\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('.php')
#1 C:\xampp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('', Array, true)
#2 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(47): view('')
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#4 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-12 23:06:38 --> Invalid file: home.php
#0 C:\xampp\htdocs\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('home.php')
#1 C:\xampp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('home', Array, true)
#2 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(47): view('home')
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#4 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-12 23:09:31 --> Invalid file: home.php
#0 C:\xampp\htdocs\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('home.php')
#1 C:\xampp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('home', Array, true)
#2 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(47): view('home')
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#4 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-12 23:24:19 --> Invalid file: home.php
#0 C:\xampp\htdocs\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('home.php')
#1 C:\xampp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('home', Array, true)
#2 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(47): view('home')
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#4 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-12 23:24:44 --> Invalid file: home.php
#0 C:\xampp\htdocs\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('home.php')
#1 C:\xampp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('home', Array, true)
#2 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(47): view('home')
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#4 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-12 23:25:15 --> Invalid file: /.php
#0 C:\xampp\htdocs\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/.php')
#1 C:\xampp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('/', Array, true)
#2 C:\xampp\htdocs\ci4\app\Controllers\Auth.php(47): view('/')
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(832): App\Controllers\Auth->ak_login()
#4 C:\xampp\htdocs\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
